name: test-model

services:
  # ====================
  # Applications
  # ====================
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: final
      args:
        - API_URL=http://localhost:20002
    image: app/frontend:latest
    restart: always
    ports:
      - 20001:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  frontend-exporter:
    container_name: frontend-exporter
    image: nginx/nginx-prometheus-exporter:latest
    restart: always
    ports:
      - "22001:9113"
    command:
      - --nginx.scrape-uri=http://frontend:8080/stub_status
    depends_on:
      - frontend
    networks:
      - app-network

  apigateway:
    container_name: apigateway
    build:
      context: ./apigateway/src
      target: final
    image: app/apigateway:latest
    restart: always
    environment:
      SERVICE_URL: http://service:8080/
      KAFKA_URL: kafka:9092
      CORS_ORIGIN: http://localhost:20001
    ports:
      - 20002:8080
    networks:
      - app-network
    depends_on:
      - service
      - kafka

  service:
    container_name: service
    build:
      context: ./service/src
      target: final
    image: app/service:latest
    restart: always
    environment:
      # CORS_ORIGIN: http://localhost:20001
      REDIS_URL: redis:6379
      KAFKA_URL: kafka:9092
      SQL_SERVER: sqlserver
      SQL_SERVER_PORT: 1433
      SQL_DATABASE: TestDatabase
      SQL_USER: testuser
      SQL_PASSWORD: Test@User123
    ports:
      - 20003:8080
    networks:
      - app-network
    depends_on:
      - redis
      - kafka

  # ====================
  # SQL Server
  # ====================
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AdminPassword0000
    ports:
      - "21003:1433"
    volumes:
      - ./sqlserver/sql_data:/var/opt/mssql/data
      - ./sqlserver/init:/init
    command: [ "/bin/bash", "-c", "/opt/mssql/bin/sqlservr & /init/run.sh && tail -f /dev/null" ]
    networks:
      - app-network

  sqlserver-exporter:
    container_name: sqlserver-exporter
    image: awaragi/prometheus-mssql-exporter
    restart: always
    environment:
      SERVER: sqlserver
      USERNAME: SA
      PASSWORD: AdminPassword0000
      DEBUG: app
    ports:
      - "22007:4000"
    networks:
      - app-network

  # ====================
  # Redis
  # ====================
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "21001:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - app-network

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter
    restart: always
    ports:
      - "22002:9121"
    environment:
      REDIS_ADDR: redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  # ====================
  # Kafka
  # ====================
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_JMX_PORT: 1099
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    ports:
      - "23007:2181"
    networks:
      - app-network

  zookeeper-exporter:
    container_name: zookeeper-exporter
    image: dabealu/zookeeper-exporter:latest
    restart: always
    ports:
      - "22006:9141"
    command: --zk-hosts="zookeeper:2181"
    depends_on:
      - zookeeper
    networks:
      - app-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "21002:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network

  kafka-exporter:
    container_name: kafka-exporter
    image: danielqsj/kafka-exporter:latest
    restart: always
    command:
      - "--kafka.server=kafka:9092"
    ports:
      - "22003:9308"
    depends_on:
      - kafka
    networks:
      - app-network

  # ====================
  # Prometheus
  # ====================
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - "23001:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  # ====================
  # Elasticsearch
  # ====================
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "23002:9200"
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
    networks:
      - app-network

  elasticsearch-exporter:
    container_name: elasticsearch-exporter
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    restart: always
    command:
      - '--es.uri=http://elasticsearch:9200'
    ports:
      - "22004:9114"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  # ====================
  # Logstash
  # ====================
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.10.2
    restart: always
    ports:
      - "23003:5044" # Logstash Beats input
      - "23004:9600" # Logstash monitoring API
    environment:
      - "http.host=0.0.0.0"
      - "http.port=9600"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - elasticsearch
    networks:
      - app-network

  logstash-exporter:
    container_name: logstash-exporter
    image: kuskoman/logstash-exporter:v1.8.3
    restart: always
    environment:
      - LOGSTASH_URL=${LOGSTASH_URL:-http://logstash:9600}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    volumes:
      - ./logstash/logstash-exporter.yml:/app/config.yml
    ports:
      - "22005:9198"
    depends_on:
      - logstash
    networks:
      - app-network

  # ====================
  # Kibana
  # ====================
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.10.2
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    command: bash -c "if [ ! -d /usr/share/kibana/plugins/kibanaPrometheusExporter ]; then bin/kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/8.10.2/kibanaPrometheusExporter-8.10.2.zip && bin/kibana;else bin/kibana; fi"
    ports:
      - "23005:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  # ====================
  # Grafana
  # ====================

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "23006:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
