name: test-model

services:
  # Source Code ####################################
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: final
    ports:
      - 4561:80
    networks:
      - app-network

  apigateway:
    container_name: apigateway
    build:
      context: ./apigateway
      target: final
    environment:
      SERVICE_URL: http://service:8080/
      KAFKA_URL: kafka:9092
    ports:
      - 4562:8080
    networks:
      - app-network
    depends_on:
      - service
      - kafka

  service:
    container_name: service
    build:
      context: ./service
      target: final
    environment:
      REDIS_URL: redis:6379
      KAFKA_URL: kafka:9092
    ports:
      - 4563:8080
    extra_hosts:
      - "localhost:192.168.1.112"
    networks:
      - app-network
    depends_on:
      - redis
      - kafka

  # Redis ##########################################
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "4564:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: always
    networks:
      - app-network
  # Kafka ##########################################
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - app-network
  # Prometheus ##########################################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
  # Grafana ##########################################  
  # Logstash  ##########################################

  # Elasticsearch  ##########################################

  # Kibana  ##########################################






networks:
  app-network:
    driver: bridge # Default network driver
