name: test-model

services:
  # Source Code ####################################
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: final
    ports:
      - 4561:80
    networks:
      - app-network

  apigateway:
    container_name: apigateway
    build:
      context: ./apigateway
      target: final
    environment:
      SERVICE_URL: http://service:8080/
    ports:
      - 4562:8080
    networks:
      - app-network
    depends_on:
      - service

  service:
    container_name: service
    build:
      context: ./service
      target: final
    environment:
      REDIS_URL: redis:6379
    ports:
      - 4563:8080
    extra_hosts:
      - "localhost:192.168.1.112"
    networks:
      - app-network
    depends_on:
      - redis

  # Redis ##########################################
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "4564:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: always
    networks:
      - app-network
  # Kafka ##########################################

  # Logstash  ##########################################

  # Elasticsearch  ##########################################

  # Kibana  ##########################################

  # Prometheus ##########################################

  # Grafana ##########################################  


networks:
  app-network:
    driver: bridge # Default network driver
