{{- $namespace := .Values.namespace | default "default" -}}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $namespace }}
  name: {{ .name }}
  labels:
  {{- if .labels }}
    app: {{ .labels.app | default .name }}
  {{- end }}
spec:
  type: {{ .type }}  
  ports:
  {{- range .ports }}    
    - protocol: {{ .protocol | default "TCP"}}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name | default ""}}
  {{- end }}      
  selector:
    app: {{ .selector.app | default .name }}
---
{{- end }}