services:
  test:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    volumes:
      - ./TestResults:/app/test/TestResults
    restart: "no"

  build:
      build:
        context: ./src
        target: final
      ports:
        - 8080:8080
      depends_on:
        test:
          condition: service_completed_successfully
