global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend-exporter:9113"]

  - job_name: "apigateway"
    static_configs:
      - targets: ["apigateway:8080"]

  - job_name: "service"
    static_configs:
      - targets: ["service:8080"]

  - job_name: "sqlserver"
    static_configs:
      - targets: ["sqlserver-exporter:4000"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "zookeeper"
    static_configs:
      - targets: ["zookeeper-exporter:9141"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch-exporter:9114"]

  - job_name: "logstash"
    static_configs:
      - targets: ["logstash-exporter:9198"]        

  - job_name: "kibana"
    scrape_interval: '10s'
    static_configs:
      - targets: ["kibana:5601"]
    metrics_path: "/_prometheus/metrics"
    basic_auth:
      username: 'elastic'
      password: 'changeme'
