global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend-exporter.app.svc.cluster.local:22001"]

  - job_name: "apigateway"
    static_configs:
      - targets: ["apigateway.app.svc.cluster.local:20002"]

  - job_name: "service"
    static_configs:
      - targets: ["service.app.svc.cluster.local:20003"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter.app.svc.cluster.local:22002"]

  - job_name: "zookeeper"
    static_configs:
      - targets: ["zookeeper-exporter.app.svc.cluster.local:22006"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter.app.svc.cluster.local:22003"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch-exporter.app.svc.cluster.local:22004"]

  - job_name: "logstash"
    static_configs:
      - targets: ["logstash-exporter.app.svc.cluster.local:22005"]        

  - job_name: "kibana"
    static_configs:
      - targets: ["kibana.app.svc.cluster.local:23005"]
    metrics_path: "/_prometheus/metrics"
