global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "frontend"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]

  - job_name: "apigateway"
    static_configs:
      - targets: ["apigateway:8080"]

  - job_name: "service"
    static_configs:
      - targets: ["service:8080"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # - job_name: "zookeeper"
  #   static_configs:
  #     - targets: ["zookeeper:7000"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
