apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: apigateway
  labels:
    app: apigateway  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: localhost:5000/app/apigateway:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: apigateway
  labels:
    app: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 20002       
      targetPort: 8080  
  type: LoadBalancer    
