apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      namespace: app
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localhost:5000/app/frontend:latest
        ports:
        - containerPort: 80
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/etc/nginx/nginx.conf"
            name: config-volume
      volumes:
        - name: config-volume
          hostPath:
            path: "/mnt/nginx/nginx.conf"
            type: File
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 20001       
      targetPort: 80  
  type: LoadBalancer    
---
# ====================
# Frontend exporter
# ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: frontend-exporter
  labels:
    app: frontend-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-exporter
  template:
    metadata:
      namespace: app
      labels:
        app: frontend-exporter
    spec:
      containers:
      - name: frontend-exporter
        image: nginx/nginx-prometheus-exporter:latest
        ports:
        - containerPort: 9113        
        args:
            - "--nginx.scrape-uri=http://frontend.app.svc.cluster.local:8080/stub_status"
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: frontend-exporter
  labels:
    app: frontend-exporter
spec:
  selector:
    app: frontend-exporter
  ports:
    - protocol: TCP
      port: 22001       
      targetPort: 9113  
  type: LoadBalancer    