apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      namespace: app
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_JMX_PORT
          value: "1099"
        - name: KAFKA_OPTS
          value: "-Dzookeeper.4lw.commands.whitelist=*" 
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 23007
      targetPort: 2181
  type: LoadBalancer
---
# ====================
# Zookeeper-exporter
# ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: zookeeper-exporter
  labels:
    app: zookeeper-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-exporter
  template:
    metadata:
      namespace: app
      labels:
        app: zookeeper-exporter
    spec:
      containers:
      - name: zookeeper-exporter
        image: dabealu/zookeeper-exporter:latest
        ports:
        - containerPort: 9141
        args: ["--zk-hosts=zookeeper.app.svc.cluster.local:23007"] 
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: zookeeper-exporter
  labels:
    app: zookeeper-exporter
spec:
  selector:
    app: zookeeper-exporter
  ports:
    - protocol: TCP
      port: 22006
      targetPort: 9141
  type: LoadBalancer
---
# ====================
# Kafka
# ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      namespace: app
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        - containerPort: 21002
        env:              
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP       
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.app.svc.cluster.local:23007"        
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTER://$(POD_IP):9092,OUTER://kafka-svc.app.svc.cluster.local:21002"
        - name: KAFKA_LISTENERS
          value: "INTER://0.0.0.0:9092,OUTER://0.0.0.0:21002"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTER:PLAINTEXT,OUTER:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTER"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"

---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: kafka-svc
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 21002
      targetPort: 21002
  type: LoadBalancer
---
# ====================
# Kafka-exporter
# ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: kafka-exporter
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      namespace: app
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest
        ports:
        - containerPort: 9308
        args: ["--kafka.server=kafka-svc.app.svc.cluster.local:21002"] 
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: kafka-exporter
  labels:
    app: kafka-exporter
spec:
  selector:
    app: kafka-exporter
  ports:
    - protocol: TCP
      port: 22003
      targetPort: 9308
  type: LoadBalancer