apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      namespace: app
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
            - mountPath: "/etc/prometheus/prometheus.yml"
              name: config-volume
      volumes:
        - name: config-volume
          hostPath:
            path: "/mnt/prometheus/prometheus.k8s.yml"
            type: File
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 23001     
      targetPort: 9090
  type: LoadBalancer
