apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: service
  labels:
    app: service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      namespace: app
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: localhost:5000/app/service:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: "redis.app.svc.cluster.local:21001"
        - name: KAFKA_URL
          value: "kafka-svc.app.svc.cluster.local:21002"
        - name: SQL_SERVER
          value: "sqlserver.app.svc.cluster.local"
        - name: SQL_SERVER_PORT
          value: "21003"
        - name: SQL_DATABASE
          value: "TestDatabase"
        - name: SQL_USER
          value: "testuser"
        - name: SQL_PASSWORD
          value: "Test@User123"

---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: service
  labels:
    app: service
spec:
  selector:
    app: service
  ports:
    - protocol: TCP
      port: 20003
      targetPort: 8080
  type: LoadBalancer
