namespace: app
services:
  - name: frontend
    type: LoadBalancer
    selector:
      app: frontend
    ports:
      - port: 20001
        targetPort: 80
  - name: apigateway
    type: LoadBalancer
    selector:
      app: apigateway
    ports:
      - port: 20002
        targetPort: 8080
  - name: service
    type: LoadBalancer
    selector:
      app: service
    ports:
      - port: 20003
        targetPort: 8080
  - name: redis
    type: LoadBalancer
    selector:
      app: redis
    ports:
      - port: 21001
        targetPort: 6379
  - name: zookeeper
    type: LoadBalancer
    selector:
      app: zookeeper
    ports:
      - port: 23007
        targetPort: 2181
  - name: kafka-svc
    type: LoadBalancer
    selector:
      app: kafka
    ports:
      - port: 21002
        targetPort: 21002